version: '3.8'

services:
  # Motor de Base de Datos
  db:
    image: mysql:8.0
    container_name: odontos-db
    environment:
      MYSQL_DATABASE: odontos_db
      MYSQL_ROOT_PASSWORD: root_password_seguro
    volumes:
      - odontos_db_data:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      - odontos-net

  # API Core (Backend)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odontos-backend
    environment:
      - DATABASE_URL=mysql://root:root_password_seguro@db:3309/odontos_db
      - JWT_SECRET=odontos_SaaS_2025_secure_key
      - PORT=3003
      - API_KEY=TU_API_KEY_AQUI
    ports:
      - "3004:3003"
    depends_on:
      - db
    networks:
      - odontos-net

  # Interfaz Web (Frontend)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: odontos-frontend
    restart: always
    ports:
      - "2002:2000"
    depends_on:
      - backend
    networks:
      - odontos-net

networks:
  odontos-net:
    driver: bridge

volumes:
  odontos_db_data: