-- AlterTable
ALTER TABLE `PurchaseOrder` ADD COLUMN `creditDays` INTEGER NULL,
    ADD COLUMN `creditDueDate` DATETIME(3) NULL,
    ADD COLUMN `paidAmount` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `paymentStatus` VARCHAR(191) NOT NULL DEFAULT 'PAGADO',
    ADD COLUMN `paymentType` VARCHAR(191) NOT NULL DEFAULT 'CONTADO';
